### ISSUE TITLE
System failure mechanism for DE

### ISSUE THREAD

**Issue by Lorscheidt** [fiskaltrust/businesscase-de-doc#8]
What's different than in AT? What do we have to change?

**Comment by Lorscheidt** [comment]
Diese Ausfallnacherfassung, funktioniert die genauso?

**Comment by MarkusEGruber** [comment]
Hi, the system failure mechanism works exactly like it does in AT.
The only difference is that the receipts don't have to be sent to the TSE, but that happens in the fiskaltrust.middleware and shouldn't concern you on your side.

**Comment by Lorscheidt** [comment]
OK, great. Thanks a lot!

**Comment by Lorscheidt** [comment]
One last thing: So no signatures will be returned by you for receipts we'd send in a batch?
